### ISSUE TITLE
Creating a user via HTTP

### ISSUE THREAD

**Issue by Paul-Todd** [davidiamyou/kumiq-identity#1]
When I attempt to create a user using
URL:
 **localhost:8080/Users**

Body:
**{**
**"schemas":["urn:scim:schemas:core:1.0"],**
**"userName":"bjensen",**
**"externalId":"bjensen",**
**"name":{**
   **"formatted":"Ms. Barbara J Jensen III",**
   **"familyName":"Jensen",**
   **"givenName":"Barbara"**
   **}**
**}**

Headers:
**Content-Type: application/json**
**Accept: application/json**

I am getting an error 
{
  "error": "GenericException",
  "time": 1456999222,
  "message": "Content type 'application/json' not supported",
  "statusCode": 500,
  "details": null
}

And in the console:
ERROR 87585 --- [nio-8080-exec-7] c.k.i.scim.endpoint.ExceptionResolver    : Content type 'application/json' not supported

I tried without the content-type and accept headers and still it did not work.
Any suggestions? 
Do I need to define a group first?
Can I setup some initial data somewhere that will populate the inmemory store at boot?

**Comment by Paul-Todd** [comment]
For anybody that runs across this the issue is that the **ONLY** content type that is supported is:
**"application/json+scim"** - "application/scim+json" from the RFC does not work and neither does application/json.

**Comment by imulab** [comment]
Sorry Paul, I haven't been checking this repo for a while. Yes you are right, according to the SCIM documentation, 'application/json+scim' is the designated content type.
